### ISSUE TITLE
ERRO[0030] error gathering metrics: 2 error(s) occurred

### ISSUE THREAD

**Issue by nhonnguyen** [tynany/cumulus_exporter#1]
Error output on cumulus exporter:
`ERRO[0030] error gathering metrics: 2 error(s) occurred:
* [from Gatherer #2] collected metric cumulus_resource_maximum label:<name:"resource" value:"" > gauge:<value:0 >  was collected before with the same name and label values
* [from Gatherer #2] collected metric cumulus_resource_used label:<name:"resource" value:"" > gauge:<value:0 >  was collected before with the same name and label values
  source="log.go:172"`

**Comment by tynany** [comment]
Can you please provide more information, such as the platform?

**Comment by nhonnguyen** [comment]
Cumulus OS version: 3.5.3
switch brand: HP Altoline 6712-32QSFP+ x86 ONIE AC Back-to-Front Switch
Thank you.

**Comment by tynany** [comment]
I know it has been a while (sorry about that!), but are you able to show me the output of `cl-resource-query -j`?

**Comment by tynany** [comment]
Closing due to no response.
