### ISSUE TITLE
Cumulus is just like node_exporter

### ISSUE THREAD

**Issue by mmihir82** [tynany/cumulus_exporter#8]
Hello,
Is it possible to provide steps to install the .cumulus_exporter? 
So every cumulus switches will cumulus_exporter be running and point the Prometheus to that switch IP and port where cumulus_exporter is running? is that correct?
thank you for your time

**Comment by tynany** [comment]
Yes, that is correct. You can download the binaries from the [releases](https://github.com/tynany/cumulus_exporter/releases) page and then all you need to do is run the binary. If you want to set up a systemd service, you can find an example config [here](https://github.com/tynany/cumulus_exporter/blob/master/etc/cumulus_exporter.service).

**Comment by mmihir82** [comment]
Thanks,
What is the difference between node_exporter vis cumulus_exporter? Is there
any difference?

Thank you

**Comment by tynany** [comment]
Cumulus Exporter exposes Cumulus specific metrics such as sensor, resource and version information. Node Exporter exposes generic Linux metrics, such as CPU, disk, network utilisation.

**Comment by mmihir82** [comment]
Thanks for the binary, will try it out. Is it possible for you to provide the grafana dashboard json? thanks

**Comment by tynany** [comment]
What metrics do you want to graph with Grafana? I can help with the PromQL.

**Comment by mmihir82** [comment]
Hi, Looking to capture following information: protocol type (bgp) routing table, collect prefix, AS number, disk, CPU, port utilization, clag, arp entry. Maybe that is too much to ask, but mostly network related, so it is easy to pin point any issue. 
thank you. Also where to add the ./cumulus_exporter file? /usr/bin directory?

**Comment by tynany** [comment]
You can capture routing metrics using [FRR Exporter](https://github.com/tynany/frr_exporter) and host stats using [Node Exporter](https://github.com/prometheus/node_exporter). I do not know of any Prometheus exporters that capture ARP entries. I plan on including a clag in the Cumulus Exporter when I have time.
